In [1]:
#from matplotlib import pylab as plt
#fig, ax = plt.subplots(figsize=(20,7))
df = pd.read_csv('data/SCF-with-expiry.csv', parse_dates=['Date', 'Exp'], infer_datetime_format=True)
df.sort_values(['Date', 'RIC'])[df.Date>='2018-1-16'].head()


#df.query('Date >= "2018-1-2"').head()
#.plot(x='Expiry', y='Close', ax=ax)

/Users/xren/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

         RIC       Date    Close        Exp   CRIC
4135   SCFF9 2018-01-16  55950.0 2019-01-16  2019F
7985   SCFG8 2018-01-16  54420.0 2018-02-09  2018G
12361  SCFH8 2018-01-16  54600.0 2018-03-15  2018H
16961  SCFJ8 2018-01-16  54650.0 2018-04-16  2018J
21265  SCFK8 2018-01-16  54840.0 2018-05-15  2018K

In [7]:
#df = pd.read_csv('data/SCF.csv', parse_dates=['Trade Date'], infer_datetime_format=True)
#df[df.RIC=='SCFG8'].sort_values('Trade Date').tail(30)
df = pd.read_csv('data/SCF-expiry.csv', parse_dates=['Exp'], infer_datetime_format=True)
df[df.RIC=='SCFF9'].tail()
#df.loc['SCFV8'].sort_values('Exp')

       RIC   CRIC        Exp
18   SCFF9  2009F 2009-01-15
19   SCFF9  2018F 2018-11-02
242  SCFF9  2019F 2019-01-16

In [118]:
df = pd.read_csv('data/SCF-fc-3d.csv', parse_dates=['Date'], infer_datetime_format=True)
df[df.Date>='2018-1-15']

,Date,0,1,2,3,4,5,6,7,8,9,10,11
4485,2018-01-15,54320.0,54530.0,54670.0,54850.0,55020.0,55220.0,55350.0,55530.0,55840.0,55900.0,56040.0,55960.0
4486,2018-01-16,55950.0,54420.0,54600.0,54650.0,54840.0,55070.0,55140.0,55320.0,55510.0,55520.0,55640.0,55830.0
4487,2018-01-17,55360.0,53690.0,53800.0,53910.0,54060.0,54230.0,54380.0,54540.0,54640.0,54840.0,54910.0,55190.0
4488,2018-01-18,55250.0,53590.0,53680.0,53840.0,53960.0,54160.0,54270.0,54440.0,54650.0,54810.0,54960.0,55170.0
4489,2018-01-19,55140.0,53560.0,53710.0,53830.0,53970.0,54160.0,54260.0,54430.0,54590.0,54770.0,54940.0,55120.0
4490,2018-01-22,55110.0,53500.0,53600.0,53760.0,53920.0,54080.0,54200.0,54340.0,54430.0,54630.0,54870.0,55110.0
4491,2018-01-23,55260.0,53490.0,53640.0,53780.0,53950.0,54120.0,54320.0,54500.0,54710.0,54940.0,55030.0,55110.0
4492,2018-01-24,54430.0,52630.0,52760.0,52910.0,53060.0,53230.0,53390.0,53540.0,53750.0,53940.0,54050.0,54230.0
4493,2018-01-25,55420.0,53470.0,53560.0,53710.0,53960.0,54280.0,54570.0,54850.0,54890.0,55130.0,55320.0,55180.0
4494,2018-01-26,55210.0,53380.0,53550.0,53690.0,53830.0,54020.0,54190.0,54360.0,54530.0,54740.0,55000.0,55040.0
4495,2018-01-29,55250.0,53370.0,53470.0,53630.0,53800.0,54030.0,54190.0,54420.0,54630.0,54820.0,55060.0,55050.0
4496,2018-01-30,54700.0,53040.0,53260.0,53360.0,53510.0,53670.0,53890.0,53990.0,54180.0,54440.0,54550.0,54730.0
4497,2018-01-31,54840.0,52880.0,53100.0,53240.0,53380.0,53570.0,53760.0,53890.0,54070.0,54290.0,54500.0,54660.0
4498,2018-02-01,54960.0,52880.0,53140.0,53300.0,53450.0,53620.0,53840.0,53970.0,54190.0,54350.0,54550.0,54820.0
4499,2018-02-02,55020.0,53030.0,53180.0,53390.0,53500.0,53720.0,53810.0,53960.0,54370.0,54600.0,54760.0,54790.0
4500,2018-02-05,54700.0,52720.0,53020.0,53190.0,53340.0,53490.0,53690.0,53850.0,54020.0,54210.0,54390.0,54540.0
4501,2018-02-06,54920.0,52630.0,53130.0,53290.0,53450.0,53690.0,53780.0,54040.0,53970.0,54220.0,54320.0,54910.0
4502,2018-02-07,54520.0,52630.0,52890.0,53070.0,53220.0,53390.0,53480.0,53690.0,53810.0,54000.0,54240.0,54380.0
4503,2018-02-08,53640.0,51660.0,51960.0,52160.0,52310.0,52480.0,52690.0,52880.0,52990.0,53200.0,53390.0,53520.0
4504,2018-02-09,53410.0,51240.0,51620.0,51800.0,51970.0,52090.0,52330.0,52410.0,52610.0,52860.0,53030.0,53220.0
4505,2018-02-12,52990.0,53300.0,51250.0,51360.0,51550.0,51790.0,52020.0,52110.0,52250.0,52440.0,52590.0,52760.0
4506,2018-02-13,53650.0,53750.0,51710.0,51880.0,52130.0,52400.0,52460.0,52780.0,53020.0,53240.0,53490.0,53700.0
4507,2018-02-14,54280.0,54480.0,52360.0,52560.0,52760.0,52950.0,53180.0,53400.0,53580.0,53720.0,53940.0,54100.0
4508,2018-02-22,54420.0,54720.0,52520.0,52770.0,52960.0,53140.0,53330.0,53520.0,53700.0,53880.0,54080.0,54280.0
4509,2018-02-23,55450.0,55740.0,53290.0,53570.0,53790.0,54010.0,54200.0,54420.0,54690.0,54850.0,55000.0,55330.0
4510,2018-02-26,55350.0,55470.0,53190.0,53430.0,53680.0,53870.0,54060.0,54320.0,54610.0,54760.0,54860.0,55190.0
4511,2018-02-27,55120.0,55320.0,53070.0,53330.0,53540.0,53720.0,53890.0,54120.0,54350.0,54460.0,54700.0,54930.0
4512,2018-02-28,54400.0,54420.0,52490.0,52740.0,52940.0,53110.0,53290.0,53470.0,53720.0,53790.0,54060.0,54180.0
4513,2018-03-01,54140.0,54300.0,52120.0,52380.0,52560.0,52730.0,52900.0,53130.0,53300.0,53540.0,53730.0,53890.0
4514,2018-03-02,53780.0,54070.0,52060.0,52240.0,52450.0,52640.0,52810.0,52960.0,53210.0,53380.0,53590.0,53700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4649,2018-09-14,48480.0,48530.0,48600.0,48680.0,48770.0,48820.0,48810.0,48860.0,48770.0,48680.0,48600.0,48540.0
4650,2018-09-17,47970.0,47900.0,47930.0,48000.0,48170.0,48120.0,48230.0,48280.0,48380.0,48210.0,48140.0,48060.0
4651,2018-09-18,48120.0,48010.0,48050.0,48090.0,48170.0,48150.0,48350.0,48350.0,48530.0,48620.0,48400.0,48240.0
4652,2018-09-19,49190.0,49130.0,49150.0,49210.0,49230.0,49330.0,49370.0,49390.0,49410.0,49660.0,49480.0,49330.0
4653,2018-09-20,49150.0,49070.0,49140.0,49180.0,49220.0,49220.0,49320.0,49390.0,49510.0,49630.0,49440.0,49280.0
4654,2018-09-21,49230.0,49170.0,49200.0,49170.0,49260.0,49280.0,49380.0,49440.0,49560.0,49880.0,49600.0,49390.0
4655,2018-09-25,49690.0,49560.0,49590.0,49630.0,49690.0,49730.0,49830.0,49880.0,49940.0,50410.0,50180.0,49920.0
4656,2018-09-26,50110.0,49970.0,50030.0,50040.0,50110.0,50150.0,50210.0,50220.0,50290.0,50700.0,50580.0,50350.0
4657,2018-09-27,49970.0,49840.0,49880.0,49920.0,49970.0,50010.0,50010.0,50030.0,50060.0,50500.0,50390.0,50200.0
4658,2018-09-28,49670.0,49540.0,49540.0,49540.0,49630.0,49640.0,49680.0,49690.0,49700.0,50240.0,49970.0,49830.0
4659,2018-10-08,49670.0,49550.0,49600.0,49610.0,49710.0,49770.0,49710.0,49800.0,49860.0,50220.0,50020.0,49860.0
4660,2018-10-09,49980.0,49920.0,49970.0,50030.0,50070.0,50100.0,50150.0,50230.0,50210.0,50510.0,50300.0,50170.0
4661,2018-10-10,50420.0,50290.0,50200.0,50350.0,50390.0,50480.0,50490.0,50450.0,50670.0,50910.0,50700.0,50600.0
4662,2018-10-11,49910.0,49880.0,49860.0,49930.0,49800.0,49950.0,49970.0,50000.0,50070.0,50130.0,50210.0,50110.0
4663,2018-10-12,50140.0,50120.0,50110.0,50210.0,50240.0,50260.0,50320.0,50340.0,50480.0,50610.0,50490.0,50340.0
4664,2018-10-15,50430.0,50350.0,50430.0,50460.0,50520.0,50580.0,50570.0,50670.0,50760.0,50810.0,50780.0,50660.0
4665,2018-10-16,50160.0,50090.0,50050.0,50190.0,50140.0,50040.0,50230.0,50350.0,50320.0,50590.0,50510.0,50400.0
4666,2018-10-17,49840.0,49740.0,49760.0,49820.0,49850.0,49870.0,49950.0,50050.0,50080.0,50090.0,50230.0,50080.0
4667,2018-10-18,49940.0,49830.0,49850.0,49910.0,49930.0,49900.0,50020.0,50060.0,50120.0,50200.0,50280.0,50150.0
4668,2018-10-19,49770.0,49690.0,49680.0,49720.0,49760.0,49760.0,49810.0,49870.0,49970.0,50020.0,50080.0,49970.0
4669,2018-10-22,50200.0,50110.0,50100.0,50200.0,50160.0,50280.0,50280.0,50360.0,50360.0,50420.0,50450.0,50370.0
4670,2018-10-23,50160.0,50070.0,50070.0,50080.0,50120.0,50130.0,50170.0,50240.0,50270.0,50370.0,50330.0,50330.0
4671,2018-10-24,50100.0,50100.0,50170.0,50250.0,50290.0,50420.0,50370.0,50470.0,50500.0,50470.0,50090.0,50120.0
4672,2018-10-25,49740.0,49770.0,49890.0,49860.0,49920.0,50030.0,49990.0,50080.0,50310.0,50270.0,49680.0,49770.0
4673,2018-10-26,50020.0,50030.0,50120.0,50090.0,50160.0,50190.0,50260.0,50260.0,50340.0,50400.0,49930.0,50040.0
4674,2018-10-29,49900.0,49900.0,49940.0,50050.0,50030.0,50120.0,50150.0,50160.0,50340.0,50290.0,49830.0,49900.0
4675,2018-10-30,49810.0,49820.0,49850.0,49890.0,49950.0,49940.0,50030.0,50060.0,50110.0,50220.0,49680.0,49840.0
4676,2018-10-31,49090.0,49100.0,49150.0,49210.0,49270.0,49330.0,49370.0,49430.0,49450.0,49510.0,49120.0,49160.0
4677,2018-11-01,48790.0,48810.0,48810.0,48910.0,48900.0,48850.0,49040.0,49120.0,49290.0,49330.0,48720.0,48860.0
4678,2018-11-02,49300.0,49370.0,49490.0,49470.0,49310.0,49490.0,49540.0,49790.0,49730.0,49760.0,49340.0,49360.0